### PR TITLE
Adding myself to the list of developers.

### PR DESCRIPTION
**Pull request by bambams**

### CODE REVIEW

**Review by dangowans — APPROVED** [review]

**Comment by dangowans** [comment]
Thanks for the PR @bambams .  Glad to have you on the list.

**Comment by bambams** [comment]
Oh, man, what a noob. I committed with my work email. 👎

**Comment by dangowans** [comment]
Does it make me more of a noob not knowing how you know that?  :)

**Comment by bambams** [comment]
_Undefined._

**Pull request merged**
